USE DB_PERFORMANCE;
GO
SET STATISTICS IO ON;
GO

SELECT CUSTOMERS.CUSTOMERID, CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME,
		ORDERS.ORDERID, ORDERS.ORDERDATE, ORDERS.TOTALAMOUNT, ORDERS.PAYMENTMETHOD, ORDERS.STATUS
FROM CUSTOMERS
INNER JOIN ORDERS
ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID
WHERE CUSTOMERS.CUSTOMERID = 670654;
GO

SELECT ORDERID, CUSTOMERID, ORDERDATE, TOTALAMOUNT, PAYMENTMETHOD, STATUS
FROM ORDERS
WHERE ORDERDATE >= '2025-01-01'
AND ORDERDATE < '2025-12-31';
GO

SELECT PRODUCTS.CATEGORY, SUM(ORDERDETAILS.ORDERDETAILID) AS TOTAL
FROM PRODUCTS
INNER JOIN ORDERDETAILS
ON PRODUCTS.PRODUCTID = ORDERDETAILS.PRODUCTID
GROUP BY PRODUCTS.CATEGORY
GO

SELECT TOP(100) CUSTOMERS.CUSTOMERID, CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME, SUM(ORDERS.TOTALAMOUNT) AS TOTAL
FROM CUSTOMERS INNER JOIN ORDERS
ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID
GROUP BY CUSTOMERS.CUSTOMERID, CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME
ORDER BY TOTAL DESC;
GO

SELECT PRODUCTID, PRODUCTNAME, CATEGORY, BRAND, PRICE, STOCK
FROM PRODUCTS
WHERE PRICE BETWEEN 0 AND 3000
GO

SELECT CUSTOMERS.CUSTOMERID, CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME, 
	ORDERS.ORDERID, ORDERDETAILS.ORDERDETAILID, ORDERDETAILS.PRODUCTID, ORDERDETAILS.QUANTITY, ORDERDETAILS.UNITPRICE
FROM CUSTOMERS
INNER JOIN ORDERS
ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID
INNER JOIN ORDERDETAILS
ON ORDERS.ORDERID = ORDERDETAILS.ORDERID
WHERE CUSTOMERS.CUSTOMERID = 254879
GO

SELECT CUSTOMERS.COUNTRY, COUNT(ORDERS.ORDERID) AS TOTAL
FROM CUSTOMERS
INNER JOIN ORDERS
ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID
GROUP BY CUSTOMERS.COUNTRY
GO

SELECT MONTH(OrderDate) AS MONTH, SUM(TotalAmount) AS TOTAL
FROM Orders
WHERE OrderDate >= '2024-01-01'
AND OrderDate < '2025-01-01'
GROUP BY MONTH(OrderDate)
ORDER BY MONTH;
GO

SELECT TOP 10 PRODUCTS.PRODUCTID, PRODUCTS.PRODUCTNAME, COUNT(ORDERDETAILS.ORDERDETAILID) AS TOTAL
FROM PRODUCTS INNER JOIN ORDERDETAILS
ON PRODUCTS.PRODUCTID = ORDERDETAILS.PRODUCTID
GROUP BY PRODUCTS.PRODUCTID, PRODUCTS.PRODUCTNAME
ORDER BY TOTAL DESC
GO

SELECT Orders.OrderID,Orders.OrderDate,
    Customers.CustomerID,Customers.FirstName,Customers.LastName,
    Products.ProductID, Products.ProductName,
    OrderDetails.Quantity,OrderDetails.UnitPrice
FROM Orders
INNER JOIN Customers
ON Orders.CustomerID = Customers.CustomerID
INNER JOIN OrderDetails 
ON Orders.OrderID = OrderDetails.OrderID
INNER JOIN Products 
ON OrderDetails.ProductID = Products.ProductID
ORDER BY Orders.OrderID;