CREATE INDEX IX_ORDERS_CUSTOMERID
ON ORDERS(CUSTOMERID)
INCLUDE (ORDERDATE, TOTALAMOUNT, PAYMENTMETHOD, STATUS);

CREATE INDEX IX_ORDERDETAILS_PRODUCTID
ON ORDERDETAILS(PRODUCTID)
INCLUDE(QUANTITY, UNITPRICE);

CREATE INDEX IX_ORDERS_ORDERDATE
ON ORDERS(ORDERDATE)
INCLUDE(TOTALAMOUNT);

CREATE INDEX IX_PRODUCTS_PRICE
ON PRODUCTS(PRICE);

CREATE INDEX IX_ORDERDETAILS_ORDERID
ON ORDERDETAILS(ORDERID)
INCLUDE(PRODUCTID, QUANTITY, UNITPRICE);

CREATE INDEX IX_CUSTOMERS_COUNTRY
ON CUSTOMERS(COUNTRY);

CREATE INDEX IX_PRODUCTS_CATEGORY
ON PRODUCTS(CATEGORY);

CREATE INDEX IX_ORDERS_STATUS
ON ORDERS(STATUS);
